export const FETCH_TECHNOLOGY = "FETCH_TECHNOLOGY";
export const ADD_TECHNOLOGY = "ADD_TECHNOLOGY";
export const REMOVE_TECHNOLOGY = "REMOVE_TECHNOLOGY";

export const FETCH_OWNER_MOBILE = "FETCH_OWNER_MOBILE";

export const ADD_DETAIL = "ADD_DETAIL";
export const DELETE_DETAILS = "DELETE_DETAILS";
